# http://wiki.mob.com/sdk-share-android-3-0-0/
-keep class cn.sharesdk.** { *; }
-keep class com.sina.** { *; }
-keep class **.R$* { *; }
-keep class **.R { *; }
-keep class com.mob.** { *; }
-keep class m.framework.** { *; }
-dontwarn cn.sharesdk.**
-dontwarn com.sina.**
-dontwarn com.mob.**
-dontwarn **.R$*